---

author:
  name: "Cem Sakarya"
  email: "cem.sakarya.pp@gmail.com"
  bio: "Technology Compliance Risk Advisor & Auditor"

domain:
  public: false
  domain: null

resume:
  pdf: true

init:
  DB: "C:\\Users\\cemsa\\Documents\\PyDBs\\personal-webpage.db"