---

author:
  name: "Cem Sakarya"
  email: "cem.sakarya.pp@gmail.com"
  bio: "Technology Compliance Risk Advisor & Auditor"
  linkedin: "https://www.linkedin.com/in/cem-sakarya-7a0197b2/"
  github: "https://github.com/cemsakarya"

domain:
  public: false
  domain: null

resume:
  pdf: true

init:
  DB: "C:\\Users\\cemsa\\Documents\\PyDBs\\personal-webpage.db"